- hosts: all
  vars_files:
    - "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"

  tasks:
  - name: Install web-server software for different os dynamically
    package:
      name: "{{ package_name }}"
      state: present

  - name: Copy webpage
    template:
      dest: "{{ doc_root }}"
      src: index.html.j2

  - name: Start the service
    service:
      name: "{{ service_name }}"
      state: restarted

